package com.aleksiprograms.survivalofkeijo.toolbox;

public enum BodyState {
    DEAD, MELEE_ATTACK,
    STAND, AIR_STAND, STAND_MOVE_RIGHT, STAND_MOVE_LEFT, STAND_MOVE_RIGHT_REVERSE, STAND_MOVE_LEFT_REVERSE,
    CROUCH, AIR_CROUCH, CROUCH_MOVE_RIGHT, CROUCH_MOVE_LEFT, CROUCH_MOVE_RIGHT_REVERSE, CROUCH_MOVE_LEFT_REVERSE,
    PRONE, AIR_PRONE, PRONE_MOVE_RIGHT, PRONE_MOVE_LEFT, PRONE_MOVE_RIGHT_REVERSE, PRONE_MOVE_LEFT_REVERSE
}